// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_limit_state.sql

package sqlc

import (
	"context"
)

const deleteAccountLimitState = `-- name: DeleteAccountLimitState :exec
DELETE FROM account_limit_state WHERE key = $1
`

func (q *Queries) DeleteAccountLimitState(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteAccountLimitState, key)
	return err
}

const listActiveAccountLimitState = `-- name: ListActiveAccountLimitState :many
SELECT key, limited_until, limit_reason FROM account_limit_state WHERE limited_until > $1
`

type ListActiveAccountLimitStateRow struct {
	Key          string `json:"key"`
	LimitedUntil int64  `json:"limited_until"`
	LimitReason  string `json:"limit_reason"`
}

func (q *Queries) ListActiveAccountLimitState(ctx context.Context, limitedUntil int64) ([]ListActiveAccountLimitStateRow, error) {
	rows, err := q.db.Query(ctx, listActiveAccountLimitState, limitedUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAccountLimitStateRow
	for rows.Next() {
		var i ListActiveAccountLimitStateRow
		if err := rows.Scan(&i.Key, &i.LimitedUntil, &i.LimitReason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccountLimitState = `-- name: UpsertAccountLimitState :exec
INSERT INTO account_limit_state (key, limited_until, limit_reason, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE SET
  limited_until = EXCLUDED.limited_until,
  limit_reason  = EXCLUDED.limit_reason,
  updated_at    = EXCLUDED.updated_at
`

type UpsertAccountLimitStateParams struct {
	Key          string `json:"key"`
	LimitedUntil int64  `json:"limited_until"`
	LimitReason  string `json:"limit_reason"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) UpsertAccountLimitState(ctx context.Context, arg UpsertAccountLimitStateParams) error {
	_, err := q.db.Exec(ctx, upsertAccountLimitState,
		arg.Key,
		arg.LimitedUntil,
		arg.LimitReason,
		arg.UpdatedAt,
	)
	return err
}
