// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_spend_threshold.sql

package sqlc

import (
	"context"
)

const getAccountSpendThreshold = `-- name: GetAccountSpendThreshold :one
SELECT key, threshold, day FROM account_spend_threshold WHERE key = $1
`

type GetAccountSpendThresholdRow struct {
	Key       string  `json:"key"`
	Threshold float64 `json:"threshold"`
	Day       int64   `json:"day"`
}

func (q *Queries) GetAccountSpendThreshold(ctx context.Context, key string) (GetAccountSpendThresholdRow, error) {
	row := q.db.QueryRow(ctx, getAccountSpendThreshold, key)
	var i GetAccountSpendThresholdRow
	err := row.Scan(&i.Key, &i.Threshold, &i.Day)
	return i, err
}

const listAccountSpendThresholds = `-- name: ListAccountSpendThresholds :many
SELECT key, threshold, day FROM account_spend_threshold
`

type ListAccountSpendThresholdsRow struct {
	Key       string  `json:"key"`
	Threshold float64 `json:"threshold"`
	Day       int64   `json:"day"`
}

func (q *Queries) ListAccountSpendThresholds(ctx context.Context) ([]ListAccountSpendThresholdsRow, error) {
	rows, err := q.db.Query(ctx, listAccountSpendThresholds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountSpendThresholdsRow
	for rows.Next() {
		var i ListAccountSpendThresholdsRow
		if err := rows.Scan(&i.Key, &i.Threshold, &i.Day); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccountSpendThreshold = `-- name: UpsertAccountSpendThreshold :exec
INSERT INTO account_spend_threshold (key, threshold, day, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE SET
  threshold  = EXCLUDED.threshold,
  day        = EXCLUDED.day,
  updated_at = EXCLUDED.updated_at
`

type UpsertAccountSpendThresholdParams struct {
	Key       string  `json:"key"`
	Threshold float64 `json:"threshold"`
	Day       int64   `json:"day"`
	UpdatedAt int64   `json:"updated_at"`
}

func (q *Queries) UpsertAccountSpendThreshold(ctx context.Context, arg UpsertAccountSpendThresholdParams) error {
	_, err := q.db.Exec(ctx, upsertAccountSpendThreshold,
		arg.Key,
		arg.Threshold,
		arg.Day,
		arg.UpdatedAt,
	)
	return err
}
