// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts_admin.sql

package sqlc

import (
	"context"
)

const listNodeAccountsAll = `-- name: ListNodeAccountsAll :many
SELECT na.node_id, na.account_id, na.profile_id, na.enabled, na.weight, na.role, na.egress,
       n.name AS node_name, n.base_url
FROM node_accounts na
JOIN nodes n ON n.id = na.node_id
ORDER BY n.name, na.profile_id
`

type ListNodeAccountsAllRow struct {
	NodeID    string `json:"node_id"`
	AccountID string `json:"account_id"`
	ProfileID string `json:"profile_id"`
	Enabled   bool   `json:"enabled"`
	Weight    int32  `json:"weight"`
	Role      string `json:"role"`
	Egress    string `json:"egress"`
	NodeName  string `json:"node_name"`
	BaseUrl   string `json:"base_url"`
}

func (q *Queries) ListNodeAccountsAll(ctx context.Context) ([]ListNodeAccountsAllRow, error) {
	rows, err := q.db.Query(ctx, listNodeAccountsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodeAccountsAllRow
	for rows.Next() {
		var i ListNodeAccountsAllRow
		if err := rows.Scan(
			&i.NodeID,
			&i.AccountID,
			&i.ProfileID,
			&i.Enabled,
			&i.Weight,
			&i.Role,
			&i.Egress,
			&i.NodeName,
			&i.BaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
