// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, owner_id, email, subscription_type, oauth_access_enc, oauth_refresh_enc, expires_at, onboarded_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, owner_id, email, subscription_type, oauth_access_enc, oauth_refresh_enc, expires_at, status, created_at, onboarded_at, banned_at
`

type CreateAccountParams struct {
	ID               string `json:"id"`
	OwnerID          string `json:"owner_id"`
	Email            string `json:"email"`
	SubscriptionType string `json:"subscription_type"`
	OauthAccessEnc   string `json:"oauth_access_enc"`
	OauthRefreshEnc  string `json:"oauth_refresh_enc"`
	ExpiresAt        int64  `json:"expires_at"`
	OnboardedAt      int64  `json:"onboarded_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.OwnerID,
		arg.Email,
		arg.SubscriptionType,
		arg.OauthAccessEnc,
		arg.OauthRefreshEnc,
		arg.ExpiresAt,
		arg.OnboardedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Email,
		&i.SubscriptionType,
		&i.OauthAccessEnc,
		&i.OauthRefreshEnc,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.OnboardedAt,
		&i.BannedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, owner_id, email, subscription_type, oauth_access_enc, oauth_refresh_enc, expires_at, status, created_at, onboarded_at, banned_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Email,
		&i.SubscriptionType,
		&i.OauthAccessEnc,
		&i.OauthRefreshEnc,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.OnboardedAt,
		&i.BannedAt,
	)
	return i, err
}

const listAccountOwners = `-- name: ListAccountOwners :many
SELECT id, owner_id FROM accounts
`

type ListAccountOwnersRow struct {
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) ListAccountOwners(ctx context.Context) ([]ListAccountOwnersRow, error) {
	rows, err := q.db.Query(ctx, listAccountOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountOwnersRow
	for rows.Next() {
		var i ListAccountOwnersRow
		if err := rows.Scan(&i.ID, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByOwner = `-- name: ListAccountsByOwner :many
SELECT id, owner_id, email, subscription_type, oauth_access_enc, oauth_refresh_enc, expires_at, status, created_at, onboarded_at, banned_at FROM accounts WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAccountsByOwner(ctx context.Context, ownerID string) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Email,
			&i.SubscriptionType,
			&i.OauthAccessEnc,
			&i.OauthRefreshEnc,
			&i.ExpiresAt,
			&i.Status,
			&i.CreatedAt,
			&i.OnboardedAt,
			&i.BannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountExpiry = `-- name: SetAccountExpiry :exec
UPDATE accounts SET expires_at=$2 WHERE id=$1
`

type SetAccountExpiryParams struct {
	ID        string `json:"id"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) SetAccountExpiry(ctx context.Context, arg SetAccountExpiryParams) error {
	_, err := q.db.Exec(ctx, setAccountExpiry, arg.ID, arg.ExpiresAt)
	return err
}

const setAccountOwner = `-- name: SetAccountOwner :exec
UPDATE accounts SET owner_id=$2 WHERE id=$1
`

type SetAccountOwnerParams struct {
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) SetAccountOwner(ctx context.Context, arg SetAccountOwnerParams) error {
	_, err := q.db.Exec(ctx, setAccountOwner, arg.ID, arg.OwnerID)
	return err
}

const setAccountStatus = `-- name: SetAccountStatus :exec
UPDATE accounts SET status=$2, banned_at=$3 WHERE id=$1
`

type SetAccountStatusParams struct {
	ID       string `json:"id"`
	Status   string `json:"status"`
	BannedAt int64  `json:"banned_at"`
}

func (q *Queries) SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) error {
	_, err := q.db.Exec(ctx, setAccountStatus, arg.ID, arg.Status, arg.BannedAt)
	return err
}

const updateAccountCreds = `-- name: UpdateAccountCreds :exec
UPDATE accounts SET oauth_access_enc=$2, oauth_refresh_enc=$3, expires_at=$4 WHERE id=$1
`

type UpdateAccountCredsParams struct {
	ID              string `json:"id"`
	OauthAccessEnc  string `json:"oauth_access_enc"`
	OauthRefreshEnc string `json:"oauth_refresh_enc"`
	ExpiresAt       int64  `json:"expires_at"`
}

func (q *Queries) UpdateAccountCreds(ctx context.Context, arg UpdateAccountCredsParams) error {
	_, err := q.db.Exec(ctx, updateAccountCreds,
		arg.ID,
		arg.OauthAccessEnc,
		arg.OauthRefreshEnc,
		arg.ExpiresAt,
	)
	return err
}
