// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_state.sql

package sqlc

import (
	"context"
)

const listAccountState = `-- name: ListAccountState :many
SELECT node_id, profile_id, status, cooldown_until, ban_streak, fail_count, updated_at FROM account_state
`

func (q *Queries) ListAccountState(ctx context.Context) ([]AccountState, error) {
	rows, err := q.db.Query(ctx, listAccountState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountState
	for rows.Next() {
		var i AccountState
		if err := rows.Scan(
			&i.NodeID,
			&i.ProfileID,
			&i.Status,
			&i.CooldownUntil,
			&i.BanStreak,
			&i.FailCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccountState = `-- name: UpsertAccountState :exec
INSERT INTO account_state (node_id, profile_id, status, cooldown_until, ban_streak, fail_count, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT (node_id, profile_id) DO UPDATE SET
  status = EXCLUDED.status,
  cooldown_until = EXCLUDED.cooldown_until,
  ban_streak = EXCLUDED.ban_streak,
  fail_count = EXCLUDED.fail_count,
  updated_at = EXCLUDED.updated_at
`

type UpsertAccountStateParams struct {
	NodeID        string `json:"node_id"`
	ProfileID     string `json:"profile_id"`
	Status        string `json:"status"`
	CooldownUntil int64  `json:"cooldown_until"`
	BanStreak     int32  `json:"ban_streak"`
	FailCount     int32  `json:"fail_count"`
	UpdatedAt     int64  `json:"updated_at"`
}

func (q *Queries) UpsertAccountState(ctx context.Context, arg UpsertAccountStateParams) error {
	_, err := q.db.Exec(ctx, upsertAccountState,
		arg.NodeID,
		arg.ProfileID,
		arg.Status,
		arg.CooldownUntil,
		arg.BanStreak,
		arg.FailCount,
		arg.UpdatedAt,
	)
	return err
}
