// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"
)

const listAllDispatchKeys = `-- name: ListAllDispatchKeys :many
SELECT id, key_hash, salt, prefix, owner_id, label, enabled, created_at FROM dispatch_keys ORDER BY created_at DESC
`

func (q *Queries) ListAllDispatchKeys(ctx context.Context) ([]DispatchKey, error) {
	rows, err := q.db.Query(ctx, listAllDispatchKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DispatchKey
	for rows.Next() {
		var i DispatchKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyHash,
			&i.Salt,
			&i.Prefix,
			&i.OwnerID,
			&i.Label,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
