// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (ts, actor, action, target, before, after)
VALUES ($1,$2,$3,$4,$5,$6)
`

type InsertAuditParams struct {
	Ts     int64  `json:"ts"`
	Actor  string `json:"actor"`
	Action string `json:"action"`
	Target string `json:"target"`
	Before []byte `json:"before"`
	After  []byte `json:"after"`
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.Ts,
		arg.Actor,
		arg.Action,
		arg.Target,
		arg.Before,
		arg.After,
	)
	return err
}

const listRecentAudit = `-- name: ListRecentAudit :many
SELECT id, ts, actor, action, target, before, after FROM audit_log ORDER BY ts DESC, id DESC LIMIT $1
`

func (q *Queries) ListRecentAudit(ctx context.Context, limit int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listRecentAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.Before,
			&i.After,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
