// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlc

import (
	"context"
)

const addCostRollup = `-- name: AddCostRollup :exec
INSERT INTO cost_rollup (scope_type, scope_id, day, model, requests, tokens_in, tokens_out, cost_usd)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT (scope_type, scope_id, day, model) DO UPDATE SET
  requests   = cost_rollup.requests + EXCLUDED.requests,
  tokens_in  = cost_rollup.tokens_in + EXCLUDED.tokens_in,
  tokens_out = cost_rollup.tokens_out + EXCLUDED.tokens_out,
  cost_usd   = cost_rollup.cost_usd + EXCLUDED.cost_usd
`

type AddCostRollupParams struct {
	ScopeType string  `json:"scope_type"`
	ScopeID   string  `json:"scope_id"`
	Day       string  `json:"day"`
	Model     string  `json:"model"`
	Requests  int64   `json:"requests"`
	TokensIn  int64   `json:"tokens_in"`
	TokensOut int64   `json:"tokens_out"`
	CostUsd   float64 `json:"cost_usd"`
}

func (q *Queries) AddCostRollup(ctx context.Context, arg AddCostRollupParams) error {
	_, err := q.db.Exec(ctx, addCostRollup,
		arg.ScopeType,
		arg.ScopeID,
		arg.Day,
		arg.Model,
		arg.Requests,
		arg.TokensIn,
		arg.TokensOut,
		arg.CostUsd,
	)
	return err
}

const appendLedger = `-- name: AppendLedger :one
INSERT INTO billing_ledger (tenant_id, ts, type, amount_usd, balance_after, ref, note)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, tenant_id, ts, type, amount_usd, balance_after, ref, note
`

type AppendLedgerParams struct {
	TenantID     string  `json:"tenant_id"`
	Ts           int64   `json:"ts"`
	Type         string  `json:"type"`
	AmountUsd    float64 `json:"amount_usd"`
	BalanceAfter float64 `json:"balance_after"`
	Ref          string  `json:"ref"`
	Note         string  `json:"note"`
}

func (q *Queries) AppendLedger(ctx context.Context, arg AppendLedgerParams) (BillingLedger, error) {
	row := q.db.QueryRow(ctx, appendLedger,
		arg.TenantID,
		arg.Ts,
		arg.Type,
		arg.AmountUsd,
		arg.BalanceAfter,
		arg.Ref,
		arg.Note,
	)
	var i BillingLedger
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Ts,
		&i.Type,
		&i.AmountUsd,
		&i.BalanceAfter,
		&i.Ref,
		&i.Note,
	)
	return i, err
}

const createSettlement = `-- name: CreateSettlement :one
INSERT INTO settlements (id, tenant_id, period_start, period_end, gross_usd, settled_usd, status, created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, tenant_id, period_start, period_end, gross_usd, settled_usd, status, created_at, settled_at, note
`

type CreateSettlementParams struct {
	ID          string  `json:"id"`
	TenantID    string  `json:"tenant_id"`
	PeriodStart int64   `json:"period_start"`
	PeriodEnd   int64   `json:"period_end"`
	GrossUsd    float64 `json:"gross_usd"`
	SettledUsd  float64 `json:"settled_usd"`
	Status      string  `json:"status"`
	CreatedAt   int64   `json:"created_at"`
}

func (q *Queries) CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error) {
	row := q.db.QueryRow(ctx, createSettlement,
		arg.ID,
		arg.TenantID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.GrossUsd,
		arg.SettledUsd,
		arg.Status,
		arg.CreatedAt,
	)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.GrossUsd,
		&i.SettledUsd,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
		&i.Note,
	)
	return i, err
}

const listLedgerByTenant = `-- name: ListLedgerByTenant :many
SELECT id, tenant_id, ts, type, amount_usd, balance_after, ref, note FROM billing_ledger WHERE tenant_id = $1 ORDER BY ts DESC, id DESC
`

func (q *Queries) ListLedgerByTenant(ctx context.Context, tenantID string) ([]BillingLedger, error) {
	rows, err := q.db.Query(ctx, listLedgerByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingLedger
	for rows.Next() {
		var i BillingLedger
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Ts,
			&i.Type,
			&i.AmountUsd,
			&i.BalanceAfter,
			&i.Ref,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHostingRate = `-- name: SetHostingRate :exec
INSERT INTO hosting_rates (tenant_id, rate, effective_from)
VALUES ($1,$2,$3)
ON CONFLICT (tenant_id, effective_from) DO UPDATE SET rate = EXCLUDED.rate
`

type SetHostingRateParams struct {
	TenantID      string  `json:"tenant_id"`
	Rate          float64 `json:"rate"`
	EffectiveFrom int64   `json:"effective_from"`
}

func (q *Queries) SetHostingRate(ctx context.Context, arg SetHostingRateParams) error {
	_, err := q.db.Exec(ctx, setHostingRate, arg.TenantID, arg.Rate, arg.EffectiveFrom)
	return err
}

const sumFallbackSpendByOwner = `-- name: SumFallbackSpendByOwner :one
SELECT coalesce(sum(s.est_cost_usd),0)::float8 AS total
FROM fallback_spend s
JOIN fallback_channels c ON c.id = s.channel_id
WHERE c.owner_id = $1
`

func (q *Queries) SumFallbackSpendByOwner(ctx context.Context, ownerID string) (float64, error) {
	row := q.db.QueryRow(ctx, sumFallbackSpendByOwner, ownerID)
	var total float64
	err := row.Scan(&total)
	return total, err
}

const upsertFallbackSpend = `-- name: UpsertFallbackSpend :exec
INSERT INTO fallback_spend (channel_id, day, requests, est_cost_usd, balance_observed)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (channel_id, day) DO UPDATE SET
  requests = fallback_spend.requests + EXCLUDED.requests,
  est_cost_usd = fallback_spend.est_cost_usd + EXCLUDED.est_cost_usd,
  balance_observed = EXCLUDED.balance_observed
`

type UpsertFallbackSpendParams struct {
	ChannelID       string  `json:"channel_id"`
	Day             string  `json:"day"`
	Requests        int64   `json:"requests"`
	EstCostUsd      float64 `json:"est_cost_usd"`
	BalanceObserved float64 `json:"balance_observed"`
}

func (q *Queries) UpsertFallbackSpend(ctx context.Context, arg UpsertFallbackSpendParams) error {
	_, err := q.db.Exec(ctx, upsertFallbackSpend,
		arg.ChannelID,
		arg.Day,
		arg.Requests,
		arg.EstCostUsd,
		arg.BalanceObserved,
	)
	return err
}
