// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cpa_quota.sql

package sqlc

import (
	"context"
)

const listCpaQuota = `-- name: ListCpaQuota :many
SELECT account_id, five_hour_util, five_hour_resets_at, seven_day_util, seven_day_resets_at, seven_day_sonnet_util, seven_day_sonnet_resets_at, updated_at FROM cpa_account_quota
`

func (q *Queries) ListCpaQuota(ctx context.Context) ([]CpaAccountQuotum, error) {
	rows, err := q.db.Query(ctx, listCpaQuota)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaAccountQuotum
	for rows.Next() {
		var i CpaAccountQuotum
		if err := rows.Scan(
			&i.AccountID,
			&i.FiveHourUtil,
			&i.FiveHourResetsAt,
			&i.SevenDayUtil,
			&i.SevenDayResetsAt,
			&i.SevenDaySonnetUtil,
			&i.SevenDaySonnetResetsAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCpaQuota = `-- name: UpsertCpaQuota :exec
INSERT INTO cpa_account_quota (account_id, five_hour_util, five_hour_resets_at, seven_day_util, seven_day_resets_at, seven_day_sonnet_util, seven_day_sonnet_resets_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT (account_id) DO UPDATE SET
  five_hour_util = EXCLUDED.five_hour_util,
  five_hour_resets_at = EXCLUDED.five_hour_resets_at,
  seven_day_util = EXCLUDED.seven_day_util,
  seven_day_resets_at = EXCLUDED.seven_day_resets_at,
  seven_day_sonnet_util = EXCLUDED.seven_day_sonnet_util,
  seven_day_sonnet_resets_at = EXCLUDED.seven_day_sonnet_resets_at,
  updated_at = EXCLUDED.updated_at
`

type UpsertCpaQuotaParams struct {
	AccountID              string  `json:"account_id"`
	FiveHourUtil           float64 `json:"five_hour_util"`
	FiveHourResetsAt       string  `json:"five_hour_resets_at"`
	SevenDayUtil           float64 `json:"seven_day_util"`
	SevenDayResetsAt       string  `json:"seven_day_resets_at"`
	SevenDaySonnetUtil     float64 `json:"seven_day_sonnet_util"`
	SevenDaySonnetResetsAt string  `json:"seven_day_sonnet_resets_at"`
	UpdatedAt              int64   `json:"updated_at"`
}

func (q *Queries) UpsertCpaQuota(ctx context.Context, arg UpsertCpaQuotaParams) error {
	_, err := q.db.Exec(ctx, upsertCpaQuota,
		arg.AccountID,
		arg.FiveHourUtil,
		arg.FiveHourResetsAt,
		arg.SevenDayUtil,
		arg.SevenDayResetsAt,
		arg.SevenDaySonnetUtil,
		arg.SevenDaySonnetResetsAt,
		arg.UpdatedAt,
	)
	return err
}
