// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package sqlc

import (
	"context"
)

const getHostingRate = `-- name: GetHostingRate :one
SELECT rate FROM hosting_rates WHERE tenant_id = $1 ORDER BY effective_from DESC LIMIT 1
`

func (q *Queries) GetHostingRate(ctx context.Context, tenantID string) (float64, error) {
	row := q.db.QueryRow(ctx, getHostingRate, tenantID)
	var rate float64
	err := row.Scan(&rate)
	return rate, err
}

const listTenantsBasic = `-- name: ListTenantsBasic :many
SELECT id, username, role FROM tenants ORDER BY created_at
`

type ListTenantsBasicRow struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Role     string `json:"role"`
}

func (q *Queries) ListTenantsBasic(ctx context.Context) ([]ListTenantsBasicRow, error) {
	rows, err := q.db.Query(ctx, listTenantsBasic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantsBasicRow
	for rows.Next() {
		var i ListTenantsBasicRow
		if err := rows.Scan(&i.ID, &i.Username, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumAllCost = `-- name: SumAllCost :one
SELECT coalesce(sum(cost_usd),0)::float8 AS total FROM cost_rollup
`

func (q *Queries) SumAllCost(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, sumAllCost)
	var total float64
	err := row.Scan(&total)
	return total, err
}

const todayDispatchByModel = `-- name: TodayDispatchByModel :many
SELECT model,
       count(*)::int AS requests,
       coalesce(sum(tokens_in),0)::bigint AS tokens_in,
       coalesce(sum(tokens_out),0)::bigint AS tokens_out,
       sum(CASE WHEN status='ok' THEN 1 ELSE 0 END)::int AS ok
FROM dispatch_logs WHERE ts >= $1
GROUP BY model ORDER BY requests DESC
`

type TodayDispatchByModelRow struct {
	Model     string `json:"model"`
	Requests  int32  `json:"requests"`
	TokensIn  int64  `json:"tokens_in"`
	TokensOut int64  `json:"tokens_out"`
	Ok        int32  `json:"ok"`
}

func (q *Queries) TodayDispatchByModel(ctx context.Context, ts int64) ([]TodayDispatchByModelRow, error) {
	rows, err := q.db.Query(ctx, todayDispatchByModel, ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodayDispatchByModelRow
	for rows.Next() {
		var i TodayDispatchByModelRow
		if err := rows.Scan(
			&i.Model,
			&i.Requests,
			&i.TokensIn,
			&i.TokensOut,
			&i.Ok,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
