// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: desired.sql

package sqlc

import (
	"context"
)

const getDesiredFeatures = `-- name: GetDesiredFeatures :one
SELECT features FROM desired_features WHERE id = 1
`

func (q *Queries) GetDesiredFeatures(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDesiredFeatures)
	var features []byte
	err := row.Scan(&features)
	return features, err
}

const setDesiredFeatures = `-- name: SetDesiredFeatures :exec
INSERT INTO desired_features (id, features, updated_at) VALUES (1, $1, $2)
ON CONFLICT (id) DO UPDATE SET features = EXCLUDED.features, updated_at = EXCLUDED.updated_at
`

type SetDesiredFeaturesParams struct {
	Features  []byte `json:"features"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) SetDesiredFeatures(ctx context.Context, arg SetDesiredFeaturesParams) error {
	_, err := q.db.Exec(ctx, setDesiredFeatures, arg.Features, arg.UpdatedAt)
	return err
}
