// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dispatch_logs.sql

package sqlc

import (
	"context"
)

const insertDispatchLog = `-- name: InsertDispatchLog :exec
INSERT INTO dispatch_logs (ts, owner_id, model, target, profile_id, status, http_status, latency_ms, tokens_in, tokens_out, fallback_reason)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
`

type InsertDispatchLogParams struct {
	Ts             int64  `json:"ts"`
	OwnerID        string `json:"owner_id"`
	Model          string `json:"model"`
	Target         string `json:"target"`
	ProfileID      string `json:"profile_id"`
	Status         string `json:"status"`
	HttpStatus     int32  `json:"http_status"`
	LatencyMs      int64  `json:"latency_ms"`
	TokensIn       int64  `json:"tokens_in"`
	TokensOut      int64  `json:"tokens_out"`
	FallbackReason string `json:"fallback_reason"`
}

func (q *Queries) InsertDispatchLog(ctx context.Context, arg InsertDispatchLogParams) error {
	_, err := q.db.Exec(ctx, insertDispatchLog,
		arg.Ts,
		arg.OwnerID,
		arg.Model,
		arg.Target,
		arg.ProfileID,
		arg.Status,
		arg.HttpStatus,
		arg.LatencyMs,
		arg.TokensIn,
		arg.TokensOut,
		arg.FallbackReason,
	)
	return err
}

const listRecentDispatchLogs = `-- name: ListRecentDispatchLogs :many
SELECT id, ts, owner_id, model, target, profile_id, status, http_status, latency_ms, tokens_in, tokens_out, fallback_reason, created_at FROM dispatch_logs ORDER BY ts DESC LIMIT $1
`

func (q *Queries) ListRecentDispatchLogs(ctx context.Context, limit int32) ([]DispatchLog, error) {
	rows, err := q.db.Query(ctx, listRecentDispatchLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DispatchLog
	for rows.Next() {
		var i DispatchLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.OwnerID,
			&i.Model,
			&i.Target,
			&i.ProfileID,
			&i.Status,
			&i.HttpStatus,
			&i.LatencyMs,
			&i.TokensIn,
			&i.TokensOut,
			&i.FallbackReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
