// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dispatch_logs.sql

package sqlc

import (
	"context"
)

const countDispatchLogs = `-- name: CountDispatchLogs :one
SELECT count(*) FROM dispatch_logs
`

func (q *Queries) CountDispatchLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDispatchLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDispatchLogsByOwner = `-- name: CountDispatchLogsByOwner :one
SELECT count(*) FROM dispatch_logs WHERE owner_id = $1
`

func (q *Queries) CountDispatchLogsByOwner(ctx context.Context, ownerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countDispatchLogsByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDispatchLogsByOwnerSince = `-- name: CountDispatchLogsByOwnerSince :one
SELECT count(*) FROM dispatch_logs WHERE owner_id = $1 AND ts >= $2
`

type CountDispatchLogsByOwnerSinceParams struct {
	OwnerID string `json:"owner_id"`
	Ts      int64  `json:"ts"`
}

func (q *Queries) CountDispatchLogsByOwnerSince(ctx context.Context, arg CountDispatchLogsByOwnerSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDispatchLogsByOwnerSince, arg.OwnerID, arg.Ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDispatchLogsSince = `-- name: CountDispatchLogsSince :one
SELECT count(*) FROM dispatch_logs WHERE ts >= $1
`

func (q *Queries) CountDispatchLogsSince(ctx context.Context, ts int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDispatchLogsSince, ts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertDispatchLog = `-- name: InsertDispatchLog :exec
INSERT INTO dispatch_logs (ts, owner_id, model, target, profile_id, status, http_status, latency_ms, tokens_in, tokens_out, fallback_reason, ttfb_ms, stream, cost_usd)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
`

type InsertDispatchLogParams struct {
	Ts             int64   `json:"ts"`
	OwnerID        string  `json:"owner_id"`
	Model          string  `json:"model"`
	Target         string  `json:"target"`
	ProfileID      string  `json:"profile_id"`
	Status         string  `json:"status"`
	HttpStatus     int32   `json:"http_status"`
	LatencyMs      int64   `json:"latency_ms"`
	TokensIn       int64   `json:"tokens_in"`
	TokensOut      int64   `json:"tokens_out"`
	FallbackReason string  `json:"fallback_reason"`
	TtfbMs         int64   `json:"ttfb_ms"`
	Stream         bool    `json:"stream"`
	CostUsd        float64 `json:"cost_usd"`
}

func (q *Queries) InsertDispatchLog(ctx context.Context, arg InsertDispatchLogParams) error {
	_, err := q.db.Exec(ctx, insertDispatchLog,
		arg.Ts,
		arg.OwnerID,
		arg.Model,
		arg.Target,
		arg.ProfileID,
		arg.Status,
		arg.HttpStatus,
		arg.LatencyMs,
		arg.TokensIn,
		arg.TokensOut,
		arg.FallbackReason,
		arg.TtfbMs,
		arg.Stream,
		arg.CostUsd,
	)
	return err
}

const listLogsByOwner = `-- name: ListLogsByOwner :many
SELECT id, ts, owner_id, model, target, profile_id, status, http_status, latency_ms, tokens_in, tokens_out, fallback_reason, created_at, ttfb_ms, stream, cost_usd FROM dispatch_logs WHERE owner_id = $1 ORDER BY ts DESC LIMIT $2
`

type ListLogsByOwnerParams struct {
	OwnerID string `json:"owner_id"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) ListLogsByOwner(ctx context.Context, arg ListLogsByOwnerParams) ([]DispatchLog, error) {
	rows, err := q.db.Query(ctx, listLogsByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DispatchLog
	for rows.Next() {
		var i DispatchLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.OwnerID,
			&i.Model,
			&i.Target,
			&i.ProfileID,
			&i.Status,
			&i.HttpStatus,
			&i.LatencyMs,
			&i.TokensIn,
			&i.TokensOut,
			&i.FallbackReason,
			&i.CreatedAt,
			&i.TtfbMs,
			&i.Stream,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDispatchLogs = `-- name: ListRecentDispatchLogs :many
SELECT id, ts, owner_id, model, target, profile_id, status, http_status, latency_ms, tokens_in, tokens_out, fallback_reason, created_at, ttfb_ms, stream, cost_usd FROM dispatch_logs ORDER BY ts DESC LIMIT $1
`

func (q *Queries) ListRecentDispatchLogs(ctx context.Context, limit int32) ([]DispatchLog, error) {
	rows, err := q.db.Query(ctx, listRecentDispatchLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DispatchLog
	for rows.Next() {
		var i DispatchLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.OwnerID,
			&i.Model,
			&i.Target,
			&i.ProfileID,
			&i.Status,
			&i.HttpStatus,
			&i.LatencyMs,
			&i.TokensIn,
			&i.TokensOut,
			&i.FallbackReason,
			&i.CreatedAt,
			&i.TtfbMs,
			&i.Stream,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todayDispatchForOwner = `-- name: TodayDispatchForOwner :one
SELECT count(*)::bigint AS requests, coalesce(sum(cost_usd),0)::float8 AS cost
FROM dispatch_logs WHERE owner_id = $1 AND ts >= $2
`

type TodayDispatchForOwnerParams struct {
	OwnerID string `json:"owner_id"`
	Ts      int64  `json:"ts"`
}

type TodayDispatchForOwnerRow struct {
	Requests int64   `json:"requests"`
	Cost     float64 `json:"cost"`
}

func (q *Queries) TodayDispatchForOwner(ctx context.Context, arg TodayDispatchForOwnerParams) (TodayDispatchForOwnerRow, error) {
	row := q.db.QueryRow(ctx, todayDispatchForOwner, arg.OwnerID, arg.Ts)
	var i TodayDispatchForOwnerRow
	err := row.Scan(&i.Requests, &i.Cost)
	return i, err
}
