// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dispatch_keys.sql

package sqlc

import (
	"context"
)

const createDispatchKey = `-- name: CreateDispatchKey :one
INSERT INTO dispatch_keys (id, key_hash, salt, prefix, owner_id, label)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, key_hash, salt, prefix, owner_id, label, enabled, created_at
`

type CreateDispatchKeyParams struct {
	ID      string `json:"id"`
	KeyHash string `json:"key_hash"`
	Salt    string `json:"salt"`
	Prefix  string `json:"prefix"`
	OwnerID string `json:"owner_id"`
	Label   string `json:"label"`
}

func (q *Queries) CreateDispatchKey(ctx context.Context, arg CreateDispatchKeyParams) (DispatchKey, error) {
	row := q.db.QueryRow(ctx, createDispatchKey,
		arg.ID,
		arg.KeyHash,
		arg.Salt,
		arg.Prefix,
		arg.OwnerID,
		arg.Label,
	)
	var i DispatchKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.Salt,
		&i.Prefix,
		&i.OwnerID,
		&i.Label,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const disableDispatchKey = `-- name: DisableDispatchKey :exec
UPDATE dispatch_keys SET enabled = FALSE WHERE id = $1
`

func (q *Queries) DisableDispatchKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, disableDispatchKey, id)
	return err
}

const getDispatchKeysByPrefix = `-- name: GetDispatchKeysByPrefix :many
SELECT id, key_hash, salt, prefix, owner_id, label, enabled, created_at FROM dispatch_keys WHERE prefix = $1 AND enabled = TRUE
`

func (q *Queries) GetDispatchKeysByPrefix(ctx context.Context, prefix string) ([]DispatchKey, error) {
	rows, err := q.db.Query(ctx, getDispatchKeysByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DispatchKey
	for rows.Next() {
		var i DispatchKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyHash,
			&i.Salt,
			&i.Prefix,
			&i.OwnerID,
			&i.Label,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDispatchKeysByOwner = `-- name: ListDispatchKeysByOwner :many
SELECT id, key_hash, salt, prefix, owner_id, label, enabled, created_at FROM dispatch_keys WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDispatchKeysByOwner(ctx context.Context, ownerID string) ([]DispatchKey, error) {
	rows, err := q.db.Query(ctx, listDispatchKeysByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DispatchKey
	for rows.Next() {
		var i DispatchKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyHash,
			&i.Salt,
			&i.Prefix,
			&i.OwnerID,
			&i.Label,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
