// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"
)

const getBanEpisodesForProfile = `-- name: GetBanEpisodesForProfile :many
SELECT id, node_id, profile_id, banned_at, recovered_at, survival_ms, detail FROM ban_episodes WHERE node_id = $1 AND profile_id = $2 ORDER BY banned_at DESC LIMIT 10
`

type GetBanEpisodesForProfileParams struct {
	NodeID    string `json:"node_id"`
	ProfileID string `json:"profile_id"`
}

func (q *Queries) GetBanEpisodesForProfile(ctx context.Context, arg GetBanEpisodesForProfileParams) ([]BanEpisode, error) {
	rows, err := q.db.Query(ctx, getBanEpisodesForProfile, arg.NodeID, arg.ProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BanEpisode
	for rows.Next() {
		var i BanEpisode
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ProfileID,
			&i.BannedAt,
			&i.RecoveredAt,
			&i.SurvivalMs,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBanEpisode = `-- name: InsertBanEpisode :exec
INSERT INTO ban_episodes (node_id, profile_id, banned_at, detail) VALUES ($1,$2,$3,$4)
`

type InsertBanEpisodeParams struct {
	NodeID    string `json:"node_id"`
	ProfileID string `json:"profile_id"`
	BannedAt  int64  `json:"banned_at"`
	Detail    []byte `json:"detail"`
}

func (q *Queries) InsertBanEpisode(ctx context.Context, arg InsertBanEpisodeParams) error {
	_, err := q.db.Exec(ctx, insertBanEpisode,
		arg.NodeID,
		arg.ProfileID,
		arg.BannedAt,
		arg.Detail,
	)
	return err
}

const insertDispatchEvent = `-- name: InsertDispatchEvent :exec
INSERT INTO dispatch_events (ts, type, target, owner_id, detail) VALUES ($1,$2,$3,$4,$5)
`

type InsertDispatchEventParams struct {
	Ts      int64  `json:"ts"`
	Type    string `json:"type"`
	Target  string `json:"target"`
	OwnerID string `json:"owner_id"`
	Detail  []byte `json:"detail"`
}

func (q *Queries) InsertDispatchEvent(ctx context.Context, arg InsertDispatchEventParams) error {
	_, err := q.db.Exec(ctx, insertDispatchEvent,
		arg.Ts,
		arg.Type,
		arg.Target,
		arg.OwnerID,
		arg.Detail,
	)
	return err
}

const listEventsByOwner = `-- name: ListEventsByOwner :many
SELECT id, ts, type, target, owner_id, detail FROM dispatch_events WHERE owner_id = $1 ORDER BY ts DESC, id DESC LIMIT $2
`

type ListEventsByOwnerParams struct {
	OwnerID string `json:"owner_id"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) ListEventsByOwner(ctx context.Context, arg ListEventsByOwnerParams) ([]DispatchEvent, error) {
	rows, err := q.db.Query(ctx, listEventsByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DispatchEvent
	for rows.Next() {
		var i DispatchEvent
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Type,
			&i.Target,
			&i.OwnerID,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentEvents = `-- name: ListRecentEvents :many
SELECT id, ts, type, target, owner_id, detail FROM dispatch_events ORDER BY ts DESC, id DESC LIMIT $1
`

func (q *Queries) ListRecentEvents(ctx context.Context, limit int32) ([]DispatchEvent, error) {
	rows, err := q.db.Query(ctx, listRecentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DispatchEvent
	for rows.Next() {
		var i DispatchEvent
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Type,
			&i.Target,
			&i.OwnerID,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverBanEpisode = `-- name: RecoverBanEpisode :exec
UPDATE ban_episodes SET recovered_at = $3, survival_ms = $3 - banned_at
WHERE node_id = $1 AND profile_id = $2 AND recovered_at = 0
`

type RecoverBanEpisodeParams struct {
	NodeID      string `json:"node_id"`
	ProfileID   string `json:"profile_id"`
	RecoveredAt int64  `json:"recovered_at"`
}

func (q *Queries) RecoverBanEpisode(ctx context.Context, arg RecoverBanEpisodeParams) error {
	_, err := q.db.Exec(ctx, recoverBanEpisode, arg.NodeID, arg.ProfileID, arg.RecoveredAt)
	return err
}
