// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fallback_channels.sql

package sqlc

import (
	"context"
)

const createFallbackChannel = `-- name: CreateFallbackChannel :one
INSERT INTO fallback_channels (id, owner_id, group_id, name, base_url, api_key, priority, weight, max_concurrent, cooldown_ms, price_threshold, model_allowlist, balance_token, balance_user_id, balance_alert_usd)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
RETURNING id, owner_id, group_id, name, base_url, api_key, priority, weight, max_concurrent, cooldown_ms, price_threshold, model_allowlist, enabled, created_at, balance_token, balance_user_id, balance_alert_usd, balance_usd, balance_checked_at, balance_error
`

type CreateFallbackChannelParams struct {
	ID              string  `json:"id"`
	OwnerID         string  `json:"owner_id"`
	GroupID         string  `json:"group_id"`
	Name            string  `json:"name"`
	BaseUrl         string  `json:"base_url"`
	ApiKey          string  `json:"api_key"`
	Priority        int32   `json:"priority"`
	Weight          int32   `json:"weight"`
	MaxConcurrent   int32   `json:"max_concurrent"`
	CooldownMs      int64   `json:"cooldown_ms"`
	PriceThreshold  float64 `json:"price_threshold"`
	ModelAllowlist  string  `json:"model_allowlist"`
	BalanceToken    string  `json:"balance_token"`
	BalanceUserID   string  `json:"balance_user_id"`
	BalanceAlertUsd float64 `json:"balance_alert_usd"`
}

func (q *Queries) CreateFallbackChannel(ctx context.Context, arg CreateFallbackChannelParams) (FallbackChannel, error) {
	row := q.db.QueryRow(ctx, createFallbackChannel,
		arg.ID,
		arg.OwnerID,
		arg.GroupID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Priority,
		arg.Weight,
		arg.MaxConcurrent,
		arg.CooldownMs,
		arg.PriceThreshold,
		arg.ModelAllowlist,
		arg.BalanceToken,
		arg.BalanceUserID,
		arg.BalanceAlertUsd,
	)
	var i FallbackChannel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.GroupID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Priority,
		&i.Weight,
		&i.MaxConcurrent,
		&i.CooldownMs,
		&i.PriceThreshold,
		&i.ModelAllowlist,
		&i.Enabled,
		&i.CreatedAt,
		&i.BalanceToken,
		&i.BalanceUserID,
		&i.BalanceAlertUsd,
		&i.BalanceUsd,
		&i.BalanceCheckedAt,
		&i.BalanceError,
	)
	return i, err
}

const deleteFallbackChannel = `-- name: DeleteFallbackChannel :exec
DELETE FROM fallback_channels WHERE id=$1
`

func (q *Queries) DeleteFallbackChannel(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFallbackChannel, id)
	return err
}

const getFallbackChannel = `-- name: GetFallbackChannel :one
SELECT id, owner_id, group_id, name, base_url, api_key, priority, weight, max_concurrent, cooldown_ms, price_threshold, model_allowlist, enabled, created_at, balance_token, balance_user_id, balance_alert_usd, balance_usd, balance_checked_at, balance_error FROM fallback_channels WHERE id=$1
`

func (q *Queries) GetFallbackChannel(ctx context.Context, id string) (FallbackChannel, error) {
	row := q.db.QueryRow(ctx, getFallbackChannel, id)
	var i FallbackChannel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.GroupID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Priority,
		&i.Weight,
		&i.MaxConcurrent,
		&i.CooldownMs,
		&i.PriceThreshold,
		&i.ModelAllowlist,
		&i.Enabled,
		&i.CreatedAt,
		&i.BalanceToken,
		&i.BalanceUserID,
		&i.BalanceAlertUsd,
		&i.BalanceUsd,
		&i.BalanceCheckedAt,
		&i.BalanceError,
	)
	return i, err
}

const getFallbackSpendToday = `-- name: GetFallbackSpendToday :one
SELECT coalesce(sum(requests),0)::bigint AS requests, coalesce(sum(est_cost_usd),0)::float8 AS cost
FROM fallback_spend WHERE channel_id=$1 AND day=$2
`

type GetFallbackSpendTodayParams struct {
	ChannelID string `json:"channel_id"`
	Day       string `json:"day"`
}

type GetFallbackSpendTodayRow struct {
	Requests int64   `json:"requests"`
	Cost     float64 `json:"cost"`
}

func (q *Queries) GetFallbackSpendToday(ctx context.Context, arg GetFallbackSpendTodayParams) (GetFallbackSpendTodayRow, error) {
	row := q.db.QueryRow(ctx, getFallbackSpendToday, arg.ChannelID, arg.Day)
	var i GetFallbackSpendTodayRow
	err := row.Scan(&i.Requests, &i.Cost)
	return i, err
}

const getFallbackSpendTotal = `-- name: GetFallbackSpendTotal :one
SELECT coalesce(sum(requests),0)::bigint AS requests, coalesce(sum(est_cost_usd),0)::float8 AS cost
FROM fallback_spend WHERE channel_id=$1
`

type GetFallbackSpendTotalRow struct {
	Requests int64   `json:"requests"`
	Cost     float64 `json:"cost"`
}

func (q *Queries) GetFallbackSpendTotal(ctx context.Context, channelID string) (GetFallbackSpendTotalRow, error) {
	row := q.db.QueryRow(ctx, getFallbackSpendTotal, channelID)
	var i GetFallbackSpendTotalRow
	err := row.Scan(&i.Requests, &i.Cost)
	return i, err
}

const listAllFallbackChannels = `-- name: ListAllFallbackChannels :many
SELECT id, owner_id, group_id, name, base_url, api_key, priority, weight, max_concurrent, cooldown_ms, price_threshold, model_allowlist, enabled, created_at, balance_token, balance_user_id, balance_alert_usd, balance_usd, balance_checked_at, balance_error FROM fallback_channels ORDER BY priority, created_at
`

func (q *Queries) ListAllFallbackChannels(ctx context.Context) ([]FallbackChannel, error) {
	rows, err := q.db.Query(ctx, listAllFallbackChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FallbackChannel
	for rows.Next() {
		var i FallbackChannel
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.GroupID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKey,
			&i.Priority,
			&i.Weight,
			&i.MaxConcurrent,
			&i.CooldownMs,
			&i.PriceThreshold,
			&i.ModelAllowlist,
			&i.Enabled,
			&i.CreatedAt,
			&i.BalanceToken,
			&i.BalanceUserID,
			&i.BalanceAlertUsd,
			&i.BalanceUsd,
			&i.BalanceCheckedAt,
			&i.BalanceError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledFallbackChannels = `-- name: ListEnabledFallbackChannels :many
SELECT id, owner_id, group_id, name, base_url, api_key, priority, weight, max_concurrent, cooldown_ms, price_threshold, model_allowlist, enabled, created_at, balance_token, balance_user_id, balance_alert_usd, balance_usd, balance_checked_at, balance_error FROM fallback_channels WHERE enabled = TRUE ORDER BY priority, created_at
`

func (q *Queries) ListEnabledFallbackChannels(ctx context.Context) ([]FallbackChannel, error) {
	rows, err := q.db.Query(ctx, listEnabledFallbackChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FallbackChannel
	for rows.Next() {
		var i FallbackChannel
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.GroupID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKey,
			&i.Priority,
			&i.Weight,
			&i.MaxConcurrent,
			&i.CooldownMs,
			&i.PriceThreshold,
			&i.ModelAllowlist,
			&i.Enabled,
			&i.CreatedAt,
			&i.BalanceToken,
			&i.BalanceUserID,
			&i.BalanceAlertUsd,
			&i.BalanceUsd,
			&i.BalanceCheckedAt,
			&i.BalanceError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFallbackChannelsByOwner = `-- name: ListFallbackChannelsByOwner :many
SELECT id, owner_id, group_id, name, base_url, api_key, priority, weight, max_concurrent, cooldown_ms, price_threshold, model_allowlist, enabled, created_at, balance_token, balance_user_id, balance_alert_usd, balance_usd, balance_checked_at, balance_error FROM fallback_channels WHERE owner_id = $1 ORDER BY priority, created_at
`

func (q *Queries) ListFallbackChannelsByOwner(ctx context.Context, ownerID string) ([]FallbackChannel, error) {
	rows, err := q.db.Query(ctx, listFallbackChannelsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FallbackChannel
	for rows.Next() {
		var i FallbackChannel
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.GroupID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKey,
			&i.Priority,
			&i.Weight,
			&i.MaxConcurrent,
			&i.CooldownMs,
			&i.PriceThreshold,
			&i.ModelAllowlist,
			&i.Enabled,
			&i.CreatedAt,
			&i.BalanceToken,
			&i.BalanceUserID,
			&i.BalanceAlertUsd,
			&i.BalanceUsd,
			&i.BalanceCheckedAt,
			&i.BalanceError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFallbackBalance = `-- name: SetFallbackBalance :exec
UPDATE fallback_channels SET balance_usd=$2, balance_checked_at=$3, balance_error=$4 WHERE id=$1
`

type SetFallbackBalanceParams struct {
	ID               string  `json:"id"`
	BalanceUsd       float64 `json:"balance_usd"`
	BalanceCheckedAt int64   `json:"balance_checked_at"`
	BalanceError     string  `json:"balance_error"`
}

func (q *Queries) SetFallbackBalance(ctx context.Context, arg SetFallbackBalanceParams) error {
	_, err := q.db.Exec(ctx, setFallbackBalance,
		arg.ID,
		arg.BalanceUsd,
		arg.BalanceCheckedAt,
		arg.BalanceError,
	)
	return err
}

const setFallbackChannelEnabled = `-- name: SetFallbackChannelEnabled :exec
UPDATE fallback_channels SET enabled=$2 WHERE id=$1
`

type SetFallbackChannelEnabledParams struct {
	ID      string `json:"id"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) SetFallbackChannelEnabled(ctx context.Context, arg SetFallbackChannelEnabledParams) error {
	_, err := q.db.Exec(ctx, setFallbackChannelEnabled, arg.ID, arg.Enabled)
	return err
}

const updateFallbackChannel = `-- name: UpdateFallbackChannel :exec
UPDATE fallback_channels SET name=$2, base_url=$3, api_key=$4, priority=$5, weight=$6,
  max_concurrent=$7, cooldown_ms=$8, price_threshold=$9, model_allowlist=$10,
  balance_token=$11, balance_user_id=$12, balance_alert_usd=$13
WHERE id=$1
`

type UpdateFallbackChannelParams struct {
	ID              string  `json:"id"`
	Name            string  `json:"name"`
	BaseUrl         string  `json:"base_url"`
	ApiKey          string  `json:"api_key"`
	Priority        int32   `json:"priority"`
	Weight          int32   `json:"weight"`
	MaxConcurrent   int32   `json:"max_concurrent"`
	CooldownMs      int64   `json:"cooldown_ms"`
	PriceThreshold  float64 `json:"price_threshold"`
	ModelAllowlist  string  `json:"model_allowlist"`
	BalanceToken    string  `json:"balance_token"`
	BalanceUserID   string  `json:"balance_user_id"`
	BalanceAlertUsd float64 `json:"balance_alert_usd"`
}

func (q *Queries) UpdateFallbackChannel(ctx context.Context, arg UpdateFallbackChannelParams) error {
	_, err := q.db.Exec(ctx, updateFallbackChannel,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Priority,
		arg.Weight,
		arg.MaxConcurrent,
		arg.CooldownMs,
		arg.PriceThreshold,
		arg.ModelAllowlist,
		arg.BalanceToken,
		arg.BalanceUserID,
		arg.BalanceAlertUsd,
	)
	return err
}
