// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fallback_channels.sql

package sqlc

import (
	"context"
)

const createFallbackChannel = `-- name: CreateFallbackChannel :one
INSERT INTO fallback_channels (id, owner_id, group_id, name, base_url, api_key, priority, weight, max_concurrent, cooldown_ms, price_threshold, model_allowlist)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
RETURNING id, owner_id, group_id, name, base_url, api_key, priority, weight, max_concurrent, cooldown_ms, price_threshold, model_allowlist, enabled, created_at
`

type CreateFallbackChannelParams struct {
	ID             string  `json:"id"`
	OwnerID        string  `json:"owner_id"`
	GroupID        string  `json:"group_id"`
	Name           string  `json:"name"`
	BaseUrl        string  `json:"base_url"`
	ApiKey         string  `json:"api_key"`
	Priority       int32   `json:"priority"`
	Weight         int32   `json:"weight"`
	MaxConcurrent  int32   `json:"max_concurrent"`
	CooldownMs     int64   `json:"cooldown_ms"`
	PriceThreshold float64 `json:"price_threshold"`
	ModelAllowlist string  `json:"model_allowlist"`
}

func (q *Queries) CreateFallbackChannel(ctx context.Context, arg CreateFallbackChannelParams) (FallbackChannel, error) {
	row := q.db.QueryRow(ctx, createFallbackChannel,
		arg.ID,
		arg.OwnerID,
		arg.GroupID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Priority,
		arg.Weight,
		arg.MaxConcurrent,
		arg.CooldownMs,
		arg.PriceThreshold,
		arg.ModelAllowlist,
	)
	var i FallbackChannel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.GroupID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Priority,
		&i.Weight,
		&i.MaxConcurrent,
		&i.CooldownMs,
		&i.PriceThreshold,
		&i.ModelAllowlist,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const listEnabledFallbackChannels = `-- name: ListEnabledFallbackChannels :many
SELECT id, owner_id, group_id, name, base_url, api_key, priority, weight, max_concurrent, cooldown_ms, price_threshold, model_allowlist, enabled, created_at FROM fallback_channels WHERE enabled = TRUE ORDER BY priority, created_at
`

func (q *Queries) ListEnabledFallbackChannels(ctx context.Context) ([]FallbackChannel, error) {
	rows, err := q.db.Query(ctx, listEnabledFallbackChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FallbackChannel
	for rows.Next() {
		var i FallbackChannel
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.GroupID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKey,
			&i.Priority,
			&i.Weight,
			&i.MaxConcurrent,
			&i.CooldownMs,
			&i.PriceThreshold,
			&i.ModelAllowlist,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFallbackChannelsByOwner = `-- name: ListFallbackChannelsByOwner :many
SELECT id, owner_id, group_id, name, base_url, api_key, priority, weight, max_concurrent, cooldown_ms, price_threshold, model_allowlist, enabled, created_at FROM fallback_channels WHERE owner_id = $1 ORDER BY priority, created_at
`

func (q *Queries) ListFallbackChannelsByOwner(ctx context.Context, ownerID string) ([]FallbackChannel, error) {
	rows, err := q.db.Query(ctx, listFallbackChannelsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FallbackChannel
	for rows.Next() {
		var i FallbackChannel
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.GroupID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKey,
			&i.Priority,
			&i.Weight,
			&i.MaxConcurrent,
			&i.CooldownMs,
			&i.PriceThreshold,
			&i.ModelAllowlist,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
