// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: intercepted_secrets.sql

package sqlc

import (
	"context"
)

const countInterceptedSecrets = `-- name: CountInterceptedSecrets :one
SELECT count(*) FROM intercepted_secrets
`

func (q *Queries) CountInterceptedSecrets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInterceptedSecrets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteInterceptedSecret = `-- name: DeleteInterceptedSecret :exec
DELETE FROM intercepted_secrets WHERE id = $1
`

func (q *Queries) DeleteInterceptedSecret(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInterceptedSecret, id)
	return err
}

const getInterceptedSecret = `-- name: GetInterceptedSecret :one
SELECT id, request_id, owner_id, account_key, model, secret_type, secret_value, context_line, created_at
FROM intercepted_secrets
WHERE id = $1
`

func (q *Queries) GetInterceptedSecret(ctx context.Context, id int64) (InterceptedSecret, error) {
	row := q.db.QueryRow(ctx, getInterceptedSecret, id)
	var i InterceptedSecret
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.OwnerID,
		&i.AccountKey,
		&i.Model,
		&i.SecretType,
		&i.SecretValue,
		&i.ContextLine,
		&i.CreatedAt,
	)
	return i, err
}

const insertInterceptedSecret = `-- name: InsertInterceptedSecret :exec
INSERT INTO intercepted_secrets (request_id, owner_id, account_key, model, secret_type, secret_value, context_line, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertInterceptedSecretParams struct {
	RequestID   string `json:"request_id"`
	OwnerID     string `json:"owner_id"`
	AccountKey  string `json:"account_key"`
	Model       string `json:"model"`
	SecretType  string `json:"secret_type"`
	SecretValue string `json:"secret_value"`
	ContextLine string `json:"context_line"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) InsertInterceptedSecret(ctx context.Context, arg InsertInterceptedSecretParams) error {
	_, err := q.db.Exec(ctx, insertInterceptedSecret,
		arg.RequestID,
		arg.OwnerID,
		arg.AccountKey,
		arg.Model,
		arg.SecretType,
		arg.SecretValue,
		arg.ContextLine,
		arg.CreatedAt,
	)
	return err
}

const listInterceptedSecrets = `-- name: ListInterceptedSecrets :many
SELECT id, request_id, owner_id, account_key, model, secret_type, secret_value, context_line, created_at
FROM intercepted_secrets
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListInterceptedSecretsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListInterceptedSecrets(ctx context.Context, arg ListInterceptedSecretsParams) ([]InterceptedSecret, error) {
	rows, err := q.db.Query(ctx, listInterceptedSecrets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InterceptedSecret
	for rows.Next() {
		var i InterceptedSecret
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.OwnerID,
			&i.AccountKey,
			&i.Model,
			&i.SecretType,
			&i.SecretValue,
			&i.ContextLine,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentInterceptedValues = `-- name: ListRecentInterceptedValues :many
SELECT DISTINCT secret_value FROM intercepted_secrets
WHERE owner_id = $1 AND created_at > $2
`

type ListRecentInterceptedValuesParams struct {
	OwnerID   string `json:"owner_id"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) ListRecentInterceptedValues(ctx context.Context, arg ListRecentInterceptedValuesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRecentInterceptedValues, arg.OwnerID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var secret_value string
		if err := rows.Scan(&secret_value); err != nil {
			return nil, err
		}
		items = append(items, secret_value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
