// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID               string             `json:"id"`
	OwnerID          string             `json:"owner_id"`
	Email            string             `json:"email"`
	SubscriptionType string             `json:"subscription_type"`
	OauthAccessEnc   string             `json:"oauth_access_enc"`
	OauthRefreshEnc  string             `json:"oauth_refresh_enc"`
	ExpiresAt        int64              `json:"expires_at"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	OnboardedAt      int64              `json:"onboarded_at"`
	BannedAt         int64              `json:"banned_at"`
}

type AccountState struct {
	NodeID        string `json:"node_id"`
	ProfileID     string `json:"profile_id"`
	Status        string `json:"status"`
	CooldownUntil int64  `json:"cooldown_until"`
	BanStreak     int32  `json:"ban_streak"`
	FailCount     int32  `json:"fail_count"`
	UpdatedAt     int64  `json:"updated_at"`
}

type DispatchKey struct {
	ID        string             `json:"id"`
	KeyHash   string             `json:"key_hash"`
	Salt      string             `json:"salt"`
	Prefix    string             `json:"prefix"`
	OwnerID   string             `json:"owner_id"`
	Label     string             `json:"label"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DispatchLog struct {
	ID             int64              `json:"id"`
	Ts             int64              `json:"ts"`
	OwnerID        string             `json:"owner_id"`
	Model          string             `json:"model"`
	Target         string             `json:"target"`
	ProfileID      string             `json:"profile_id"`
	Status         string             `json:"status"`
	HttpStatus     int32              `json:"http_status"`
	LatencyMs      int64              `json:"latency_ms"`
	TokensIn       int64              `json:"tokens_in"`
	TokensOut      int64              `json:"tokens_out"`
	FallbackReason string             `json:"fallback_reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type FallbackChannel struct {
	ID             string             `json:"id"`
	OwnerID        string             `json:"owner_id"`
	GroupID        string             `json:"group_id"`
	Name           string             `json:"name"`
	BaseUrl        string             `json:"base_url"`
	ApiKey         string             `json:"api_key"`
	Priority       int32              `json:"priority"`
	Weight         int32              `json:"weight"`
	MaxConcurrent  int32              `json:"max_concurrent"`
	CooldownMs     int64              `json:"cooldown_ms"`
	PriceThreshold float64            `json:"price_threshold"`
	ModelAllowlist string             `json:"model_allowlist"`
	Enabled        bool               `json:"enabled"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type GroupMember struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
	Role    string `json:"role"`
}

type Node struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	BaseUrl         string             `json:"base_url"`
	ApiKey          string             `json:"api_key"`
	MgmtKey         string             `json:"mgmt_key"`
	OwnerID         string             `json:"owner_id"`
	GroupID         string             `json:"group_id"`
	Region          string             `json:"region"`
	ShortID         string             `json:"short_id"`
	Version         string             `json:"version"`
	FingerprintSeed string             `json:"fingerprint_seed"`
	Enabled         bool               `json:"enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type NodeAccount struct {
	NodeID    string `json:"node_id"`
	AccountID string `json:"account_id"`
	ProfileID string `json:"profile_id"`
	Enabled   bool   `json:"enabled"`
	Egress    string `json:"egress"`
	Weight    int32  `json:"weight"`
	Role      string `json:"role"`
	SlotID    string `json:"slot_id"`
	PushedAt  int64  `json:"pushed_at"`
}

type NodeGroup struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	OwnerID string `json:"owner_id"`
}

type Policy struct {
	ScopeType string `json:"scope_type"`
	ScopeID   string `json:"scope_id"`
	Params    []byte `json:"params"`
	UpdatedAt int64  `json:"updated_at"`
}

type Role struct {
	Name        string `json:"name"`
	Builtin     bool   `json:"builtin"`
	Permissions []byte `json:"permissions"`
}

type Tenant struct {
	ID           string             `json:"id"`
	Username     string             `json:"username"`
	PwHash       string             `json:"pw_hash"`
	Salt         string             `json:"salt"`
	Role         string             `json:"role"`
	IngestKey    string             `json:"ingest_key"`
	MustChangePw bool               `json:"must_change_pw"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
