// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Tenant struct {
	ID           string             `json:"id"`
	Username     string             `json:"username"`
	PwHash       string             `json:"pw_hash"`
	Salt         string             `json:"salt"`
	Role         string             `json:"role"`
	IngestKey    string             `json:"ingest_key"`
	MustChangePw bool               `json:"must_change_pw"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
