// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID               string             `json:"id"`
	OwnerID          string             `json:"owner_id"`
	Email            string             `json:"email"`
	SubscriptionType string             `json:"subscription_type"`
	OauthAccessEnc   string             `json:"oauth_access_enc"`
	OauthRefreshEnc  string             `json:"oauth_refresh_enc"`
	ExpiresAt        int64              `json:"expires_at"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	OnboardedAt      int64              `json:"onboarded_at"`
	BannedAt         int64              `json:"banned_at"`
}

type AccountState struct {
	NodeID        string `json:"node_id"`
	ProfileID     string `json:"profile_id"`
	Status        string `json:"status"`
	CooldownUntil int64  `json:"cooldown_until"`
	BanStreak     int32  `json:"ban_streak"`
	FailCount     int32  `json:"fail_count"`
	UpdatedAt     int64  `json:"updated_at"`
	Permanent     bool   `json:"permanent"`
}

type AuditLog struct {
	ID     int64  `json:"id"`
	Ts     int64  `json:"ts"`
	Actor  string `json:"actor"`
	Action string `json:"action"`
	Target string `json:"target"`
	Before []byte `json:"before"`
	After  []byte `json:"after"`
}

type BanEpisode struct {
	ID          int64  `json:"id"`
	NodeID      string `json:"node_id"`
	ProfileID   string `json:"profile_id"`
	BannedAt    int64  `json:"banned_at"`
	RecoveredAt int64  `json:"recovered_at"`
	SurvivalMs  int64  `json:"survival_ms"`
	Detail      []byte `json:"detail"`
}

type BillingLedger struct {
	ID           int64   `json:"id"`
	TenantID     string  `json:"tenant_id"`
	Ts           int64   `json:"ts"`
	Type         string  `json:"type"`
	AmountUsd    float64 `json:"amount_usd"`
	BalanceAfter float64 `json:"balance_after"`
	Ref          string  `json:"ref"`
	Note         string  `json:"note"`
}

type CostRollup struct {
	ScopeType string  `json:"scope_type"`
	ScopeID   string  `json:"scope_id"`
	Day       string  `json:"day"`
	Model     string  `json:"model"`
	Requests  int64   `json:"requests"`
	TokensIn  int64   `json:"tokens_in"`
	TokensOut int64   `json:"tokens_out"`
	CostUsd   float64 `json:"cost_usd"`
}

type DesiredFeature struct {
	ID        int32  `json:"id"`
	Features  []byte `json:"features"`
	UpdatedAt int64  `json:"updated_at"`
}

type DispatchEvent struct {
	ID      int64  `json:"id"`
	Ts      int64  `json:"ts"`
	Type    string `json:"type"`
	Target  string `json:"target"`
	OwnerID string `json:"owner_id"`
	Detail  []byte `json:"detail"`
}

type DispatchKey struct {
	ID        string             `json:"id"`
	KeyHash   string             `json:"key_hash"`
	Salt      string             `json:"salt"`
	Prefix    string             `json:"prefix"`
	OwnerID   string             `json:"owner_id"`
	Label     string             `json:"label"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DispatchLog struct {
	ID             int64              `json:"id"`
	Ts             int64              `json:"ts"`
	OwnerID        string             `json:"owner_id"`
	Model          string             `json:"model"`
	Target         string             `json:"target"`
	ProfileID      string             `json:"profile_id"`
	Status         string             `json:"status"`
	HttpStatus     int32              `json:"http_status"`
	LatencyMs      int64              `json:"latency_ms"`
	TokensIn       int64              `json:"tokens_in"`
	TokensOut      int64              `json:"tokens_out"`
	FallbackReason string             `json:"fallback_reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	TtfbMs         int64              `json:"ttfb_ms"`
	Stream         bool               `json:"stream"`
	CostUsd        float64            `json:"cost_usd"`
}

type FallbackChannel struct {
	ID               string             `json:"id"`
	OwnerID          string             `json:"owner_id"`
	GroupID          string             `json:"group_id"`
	Name             string             `json:"name"`
	BaseUrl          string             `json:"base_url"`
	ApiKey           string             `json:"api_key"`
	Priority         int32              `json:"priority"`
	Weight           int32              `json:"weight"`
	MaxConcurrent    int32              `json:"max_concurrent"`
	CooldownMs       int64              `json:"cooldown_ms"`
	PriceThreshold   float64            `json:"price_threshold"`
	ModelAllowlist   string             `json:"model_allowlist"`
	Enabled          bool               `json:"enabled"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	BalanceToken     string             `json:"balance_token"`
	BalanceUserID    string             `json:"balance_user_id"`
	BalanceAlertUsd  float64            `json:"balance_alert_usd"`
	BalanceUsd       float64            `json:"balance_usd"`
	BalanceCheckedAt int64              `json:"balance_checked_at"`
	BalanceError     string             `json:"balance_error"`
}

type FallbackSpend struct {
	ChannelID       string  `json:"channel_id"`
	Day             string  `json:"day"`
	Requests        int64   `json:"requests"`
	EstCostUsd      float64 `json:"est_cost_usd"`
	BalanceObserved float64 `json:"balance_observed"`
}

type GroupMember struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
	Role    string `json:"role"`
}

type HostingRate struct {
	TenantID      string  `json:"tenant_id"`
	Rate          float64 `json:"rate"`
	EffectiveFrom int64   `json:"effective_from"`
}

type Node struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	BaseUrl         string             `json:"base_url"`
	ApiKey          string             `json:"api_key"`
	MgmtKey         string             `json:"mgmt_key"`
	OwnerID         string             `json:"owner_id"`
	GroupID         string             `json:"group_id"`
	Region          string             `json:"region"`
	ShortID         string             `json:"short_id"`
	Version         string             `json:"version"`
	FingerprintSeed string             `json:"fingerprint_seed"`
	Enabled         bool               `json:"enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type NodeAccount struct {
	NodeID    string `json:"node_id"`
	AccountID string `json:"account_id"`
	ProfileID string `json:"profile_id"`
	Enabled   bool   `json:"enabled"`
	Egress    string `json:"egress"`
	Weight    int32  `json:"weight"`
	Role      string `json:"role"`
	SlotID    string `json:"slot_id"`
	PushedAt  int64  `json:"pushed_at"`
}

type NodeGroup struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	OwnerID string `json:"owner_id"`
}

type Policy struct {
	ScopeType string `json:"scope_type"`
	ScopeID   string `json:"scope_id"`
	Params    []byte `json:"params"`
	UpdatedAt int64  `json:"updated_at"`
}

type ProvisionJob struct {
	ID        string `json:"id"`
	Host      string `json:"host"`
	Name      string `json:"name"`
	OwnerID   string `json:"owner_id"`
	Status    string `json:"status"`
	Step      string `json:"step"`
	Log       string `json:"log"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Role struct {
	Name        string `json:"name"`
	Builtin     bool   `json:"builtin"`
	Permissions []byte `json:"permissions"`
}

type Settlement struct {
	ID          string  `json:"id"`
	TenantID    string  `json:"tenant_id"`
	PeriodStart int64   `json:"period_start"`
	PeriodEnd   int64   `json:"period_end"`
	GrossUsd    float64 `json:"gross_usd"`
	SettledUsd  float64 `json:"settled_usd"`
	Status      string  `json:"status"`
	CreatedAt   int64   `json:"created_at"`
	SettledAt   int64   `json:"settled_at"`
	Note        string  `json:"note"`
}

type Slot struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	StartMin  int32              `json:"start_min"`
	EndMin    int32              `json:"end_min"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	OwnerID   string             `json:"owner_id"`
}

type Tenant struct {
	ID            string             `json:"id"`
	Username      string             `json:"username"`
	PwHash        string             `json:"pw_hash"`
	Salt          string             `json:"salt"`
	Role          string             `json:"role"`
	IngestKey     string             `json:"ingest_key"`
	MustChangePw  bool               `json:"must_change_pw"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ChannelRate   float64            `json:"channel_rate"`
	FallbackLimit int32              `json:"fallback_limit"`
}
