// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package sqlc

import (
	"context"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (id, name, base_url, api_key, mgmt_key, owner_id, group_id, region, short_id, version, fingerprint_seed, kind, passthrough, account_owner_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
RETURNING id, name, base_url, api_key, mgmt_key, owner_id, group_id, region, short_id, version, fingerprint_seed, enabled, created_at, kind, passthrough, account_owner_id
`

type CreateNodeParams struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	BaseUrl         string `json:"base_url"`
	ApiKey          string `json:"api_key"`
	MgmtKey         string `json:"mgmt_key"`
	OwnerID         string `json:"owner_id"`
	GroupID         string `json:"group_id"`
	Region          string `json:"region"`
	ShortID         string `json:"short_id"`
	Version         string `json:"version"`
	FingerprintSeed string `json:"fingerprint_seed"`
	Kind            string `json:"kind"`
	Passthrough     bool   `json:"passthrough"`
	AccountOwnerID  string `json:"account_owner_id"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKey,
		arg.MgmtKey,
		arg.OwnerID,
		arg.GroupID,
		arg.Region,
		arg.ShortID,
		arg.Version,
		arg.FingerprintSeed,
		arg.Kind,
		arg.Passthrough,
		arg.AccountOwnerID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKey,
		&i.MgmtKey,
		&i.OwnerID,
		&i.GroupID,
		&i.Region,
		&i.ShortID,
		&i.Version,
		&i.FingerprintSeed,
		&i.Enabled,
		&i.CreatedAt,
		&i.Kind,
		&i.Passthrough,
		&i.AccountOwnerID,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const getNode = `-- name: GetNode :one
SELECT id, name, base_url, api_key, mgmt_key, owner_id, group_id, region, short_id, version, fingerprint_seed, enabled, created_at, kind, passthrough, account_owner_id FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKey,
		&i.MgmtKey,
		&i.OwnerID,
		&i.GroupID,
		&i.Region,
		&i.ShortID,
		&i.Version,
		&i.FingerprintSeed,
		&i.Enabled,
		&i.CreatedAt,
		&i.Kind,
		&i.Passthrough,
		&i.AccountOwnerID,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, base_url, api_key, mgmt_key, owner_id, group_id, region, short_id, version, fingerprint_seed, enabled, created_at, kind, passthrough, account_owner_id FROM nodes ORDER BY created_at DESC
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKey,
			&i.MgmtKey,
			&i.OwnerID,
			&i.GroupID,
			&i.Region,
			&i.ShortID,
			&i.Version,
			&i.FingerprintSeed,
			&i.Enabled,
			&i.CreatedAt,
			&i.Kind,
			&i.Passthrough,
			&i.AccountOwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByOwner = `-- name: ListNodesByOwner :many
SELECT id, name, base_url, api_key, mgmt_key, owner_id, group_id, region, short_id, version, fingerprint_seed, enabled, created_at, kind, passthrough, account_owner_id FROM nodes WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListNodesByOwner(ctx context.Context, ownerID string) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKey,
			&i.MgmtKey,
			&i.OwnerID,
			&i.GroupID,
			&i.Region,
			&i.ShortID,
			&i.Version,
			&i.FingerprintSeed,
			&i.Enabled,
			&i.CreatedAt,
			&i.Kind,
			&i.Passthrough,
			&i.AccountOwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNodeAccountOwner = `-- name: SetNodeAccountOwner :exec
UPDATE nodes SET account_owner_id = $2 WHERE id = $1
`

type SetNodeAccountOwnerParams struct {
	ID             string `json:"id"`
	AccountOwnerID string `json:"account_owner_id"`
}

func (q *Queries) SetNodeAccountOwner(ctx context.Context, arg SetNodeAccountOwnerParams) error {
	_, err := q.db.Exec(ctx, setNodeAccountOwner, arg.ID, arg.AccountOwnerID)
	return err
}

const updateNodeEnabled = `-- name: UpdateNodeEnabled :exec
UPDATE nodes SET enabled = $2 WHERE id = $1
`

type UpdateNodeEnabledParams struct {
	ID      string `json:"id"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) UpdateNodeEnabled(ctx context.Context, arg UpdateNodeEnabledParams) error {
	_, err := q.db.Exec(ctx, updateNodeEnabled, arg.ID, arg.Enabled)
	return err
}
