// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_admin.sql

package sqlc

import (
	"context"
)

const setNodeEnabled = `-- name: SetNodeEnabled :exec
UPDATE nodes SET enabled = $2 WHERE id = $1
`

type SetNodeEnabledParams struct {
	ID      string `json:"id"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) SetNodeEnabled(ctx context.Context, arg SetNodeEnabledParams) error {
	_, err := q.db.Exec(ctx, setNodeEnabled, arg.ID, arg.Enabled)
	return err
}

const setNodePassthrough = `-- name: SetNodePassthrough :exec
UPDATE nodes SET passthrough = $2 WHERE id = $1
`

type SetNodePassthroughParams struct {
	ID          string `json:"id"`
	Passthrough bool   `json:"passthrough"`
}

func (q *Queries) SetNodePassthrough(ctx context.Context, arg SetNodePassthroughParams) error {
	_, err := q.db.Exec(ctx, setNodePassthrough, arg.ID, arg.Passthrough)
	return err
}
