// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_accounts.sql

package sqlc

import (
	"context"
)

const assignAccount = `-- name: AssignAccount :one
INSERT INTO node_accounts (node_id, account_id, profile_id, egress, weight, role, slot_id)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING node_id, account_id, profile_id, enabled, egress, weight, role, slot_id, pushed_at
`

type AssignAccountParams struct {
	NodeID    string `json:"node_id"`
	AccountID string `json:"account_id"`
	ProfileID string `json:"profile_id"`
	Egress    string `json:"egress"`
	Weight    int32  `json:"weight"`
	Role      string `json:"role"`
	SlotID    string `json:"slot_id"`
}

func (q *Queries) AssignAccount(ctx context.Context, arg AssignAccountParams) (NodeAccount, error) {
	row := q.db.QueryRow(ctx, assignAccount,
		arg.NodeID,
		arg.AccountID,
		arg.ProfileID,
		arg.Egress,
		arg.Weight,
		arg.Role,
		arg.SlotID,
	)
	var i NodeAccount
	err := row.Scan(
		&i.NodeID,
		&i.AccountID,
		&i.ProfileID,
		&i.Enabled,
		&i.Egress,
		&i.Weight,
		&i.Role,
		&i.SlotID,
		&i.PushedAt,
	)
	return i, err
}

const listNodeAccountsByAccount = `-- name: ListNodeAccountsByAccount :many
SELECT node_id, account_id, profile_id, enabled, egress, weight, role, slot_id, pushed_at FROM node_accounts WHERE account_id = $1
`

func (q *Queries) ListNodeAccountsByAccount(ctx context.Context, accountID string) ([]NodeAccount, error) {
	rows, err := q.db.Query(ctx, listNodeAccountsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeAccount
	for rows.Next() {
		var i NodeAccount
		if err := rows.Scan(
			&i.NodeID,
			&i.AccountID,
			&i.ProfileID,
			&i.Enabled,
			&i.Egress,
			&i.Weight,
			&i.Role,
			&i.SlotID,
			&i.PushedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeAccountsByNode = `-- name: ListNodeAccountsByNode :many
SELECT node_id, account_id, profile_id, enabled, egress, weight, role, slot_id, pushed_at FROM node_accounts WHERE node_id = $1
`

func (q *Queries) ListNodeAccountsByNode(ctx context.Context, nodeID string) ([]NodeAccount, error) {
	rows, err := q.db.Query(ctx, listNodeAccountsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeAccount
	for rows.Next() {
		var i NodeAccount
		if err := rows.Scan(
			&i.NodeID,
			&i.AccountID,
			&i.ProfileID,
			&i.Enabled,
			&i.Egress,
			&i.Weight,
			&i.Role,
			&i.SlotID,
			&i.PushedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNodeAccountEnabled = `-- name: SetNodeAccountEnabled :exec
UPDATE node_accounts SET enabled = $3 WHERE node_id = $1 AND account_id = $2
`

type SetNodeAccountEnabledParams struct {
	NodeID    string `json:"node_id"`
	AccountID string `json:"account_id"`
	Enabled   bool   `json:"enabled"`
}

func (q *Queries) SetNodeAccountEnabled(ctx context.Context, arg SetNodeAccountEnabledParams) error {
	_, err := q.db.Exec(ctx, setNodeAccountEnabled, arg.NodeID, arg.AccountID, arg.Enabled)
	return err
}

const unassignAccount = `-- name: UnassignAccount :exec
DELETE FROM node_accounts WHERE node_id = $1 AND account_id = $2
`

type UnassignAccountParams struct {
	NodeID    string `json:"node_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) UnassignAccount(ctx context.Context, arg UnassignAccountParams) error {
	_, err := q.db.Exec(ctx, unassignAccount, arg.NodeID, arg.AccountID)
	return err
}

const updateNodeAccount = `-- name: UpdateNodeAccount :exec
UPDATE node_accounts SET egress=$3, weight=$4, role=$5, enabled=$6
WHERE node_id=$1 AND account_id=$2
`

type UpdateNodeAccountParams struct {
	NodeID    string `json:"node_id"`
	AccountID string `json:"account_id"`
	Egress    string `json:"egress"`
	Weight    int32  `json:"weight"`
	Role      string `json:"role"`
	Enabled   bool   `json:"enabled"`
}

func (q *Queries) UpdateNodeAccount(ctx context.Context, arg UpdateNodeAccountParams) error {
	_, err := q.db.Exec(ctx, updateNodeAccount,
		arg.NodeID,
		arg.AccountID,
		arg.Egress,
		arg.Weight,
		arg.Role,
		arg.Enabled,
	)
	return err
}
