// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package sqlc

import (
	"context"
)

const deletePolicy = `-- name: DeletePolicy :exec
DELETE FROM policies WHERE scope_type=$1 AND scope_id=$2
`

type DeletePolicyParams struct {
	ScopeType string `json:"scope_type"`
	ScopeID   string `json:"scope_id"`
}

func (q *Queries) DeletePolicy(ctx context.Context, arg DeletePolicyParams) error {
	_, err := q.db.Exec(ctx, deletePolicy, arg.ScopeType, arg.ScopeID)
	return err
}

const listPolicies = `-- name: ListPolicies :many
SELECT scope_type, scope_id, params, updated_at FROM policies
`

func (q *Queries) ListPolicies(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ScopeType,
			&i.ScopeID,
			&i.Params,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPolicy = `-- name: UpsertPolicy :exec
INSERT INTO policies (scope_type, scope_id, params, updated_at)
VALUES ($1,$2,$3,$4)
ON CONFLICT (scope_type, scope_id) DO UPDATE SET params = EXCLUDED.params, updated_at = EXCLUDED.updated_at
`

type UpsertPolicyParams struct {
	ScopeType string `json:"scope_type"`
	ScopeID   string `json:"scope_id"`
	Params    []byte `json:"params"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) UpsertPolicy(ctx context.Context, arg UpsertPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertPolicy,
		arg.ScopeType,
		arg.ScopeID,
		arg.Params,
		arg.UpdatedAt,
	)
	return err
}
