// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provision.sql

package sqlc

import (
	"context"
)

const appendProvisionLog = `-- name: AppendProvisionLog :exec
UPDATE provision_jobs SET log = log || $1, updated_at = $2 WHERE id = $3
`

type AppendProvisionLogParams struct {
	Chunk     string `json:"chunk"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) AppendProvisionLog(ctx context.Context, arg AppendProvisionLogParams) error {
	_, err := q.db.Exec(ctx, appendProvisionLog, arg.Chunk, arg.UpdatedAt, arg.ID)
	return err
}

const createProvisionJob = `-- name: CreateProvisionJob :one
INSERT INTO provision_jobs (id, host, name, owner_id, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$5)
RETURNING id, host, name, owner_id, status, step, log, created_at, updated_at
`

type CreateProvisionJobParams struct {
	ID        string `json:"id"`
	Host      string `json:"host"`
	Name      string `json:"name"`
	OwnerID   string `json:"owner_id"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateProvisionJob(ctx context.Context, arg CreateProvisionJobParams) (ProvisionJob, error) {
	row := q.db.QueryRow(ctx, createProvisionJob,
		arg.ID,
		arg.Host,
		arg.Name,
		arg.OwnerID,
		arg.CreatedAt,
	)
	var i ProvisionJob
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Name,
		&i.OwnerID,
		&i.Status,
		&i.Step,
		&i.Log,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProvisionJob = `-- name: GetProvisionJob :one
SELECT id, host, name, owner_id, status, step, log, created_at, updated_at FROM provision_jobs WHERE id = $1
`

func (q *Queries) GetProvisionJob(ctx context.Context, id string) (ProvisionJob, error) {
	row := q.db.QueryRow(ctx, getProvisionJob, id)
	var i ProvisionJob
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Name,
		&i.OwnerID,
		&i.Status,
		&i.Step,
		&i.Log,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setProvisionStatus = `-- name: SetProvisionStatus :exec
UPDATE provision_jobs SET status = $2, step = $3, updated_at = $4 WHERE id = $1
`

type SetProvisionStatusParams struct {
	ID        string `json:"id"`
	Status    string `json:"status"`
	Step      string `json:"step"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) SetProvisionStatus(ctx context.Context, arg SetProvisionStatusParams) error {
	_, err := q.db.Exec(ctx, setProvisionStatus,
		arg.ID,
		arg.Status,
		arg.Step,
		arg.UpdatedAt,
	)
	return err
}
