// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settle.sql

package sqlc

import (
	"context"
)

const sumCostForOwner = `-- name: SumCostForOwner :one
SELECT COALESCE(SUM(cost_usd), 0)::double precision FROM cost_rollup WHERE scope_type = 'owner' AND scope_id = $1
`

func (q *Queries) SumCostForOwner(ctx context.Context, scopeID string) (float64, error) {
	row := q.db.QueryRow(ctx, sumCostForOwner, scopeID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumSettledForOwner = `-- name: SumSettledForOwner :one
SELECT COALESCE(SUM(settled_usd), 0)::double precision FROM settlements WHERE tenant_id = $1 AND status = 'paid'
`

func (q *Queries) SumSettledForOwner(ctx context.Context, tenantID string) (float64, error) {
	row := q.db.QueryRow(ctx, sumSettledForOwner, tenantID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}
