// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: slots.sql

package sqlc

import (
	"context"
)

const createSlot = `-- name: CreateSlot :one
INSERT INTO slots (id, name, start_min, end_min)
VALUES ($1, $2, $3, $4)
RETURNING id, name, start_min, end_min, enabled, created_at
`

type CreateSlotParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	StartMin int32  `json:"start_min"`
	EndMin   int32  `json:"end_min"`
}

func (q *Queries) CreateSlot(ctx context.Context, arg CreateSlotParams) (Slot, error) {
	row := q.db.QueryRow(ctx, createSlot,
		arg.ID,
		arg.Name,
		arg.StartMin,
		arg.EndMin,
	)
	var i Slot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartMin,
		&i.EndMin,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSlot = `-- name: DeleteSlot :exec
DELETE FROM slots WHERE id = $1
`

func (q *Queries) DeleteSlot(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSlot, id)
	return err
}

const listSlots = `-- name: ListSlots :many
SELECT id, name, start_min, end_min, enabled, created_at FROM slots ORDER BY name
`

func (q *Queries) ListSlots(ctx context.Context) ([]Slot, error) {
	rows, err := q.db.Query(ctx, listSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Slot
	for rows.Next() {
		var i Slot
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartMin,
			&i.EndMin,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSlotEnabled = `-- name: SetSlotEnabled :exec
UPDATE slots SET enabled = $2 WHERE id = $1
`

type SetSlotEnabledParams struct {
	ID      string `json:"id"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) SetSlotEnabled(ctx context.Context, arg SetSlotEnabledParams) error {
	_, err := q.db.Exec(ctx, setSlotEnabled, arg.ID, arg.Enabled)
	return err
}
