// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telemetry.sql

package sqlc

import (
	"context"
)

const updateNodeVersion = `-- name: UpdateNodeVersion :exec
UPDATE nodes SET version = $2 WHERE id = $1
`

type UpdateNodeVersionParams struct {
	ID      string `json:"id"`
	Version string `json:"version"`
}

func (q *Queries) UpdateNodeVersion(ctx context.Context, arg UpdateNodeVersionParams) error {
	_, err := q.db.Exec(ctx, updateNodeVersion, arg.ID, arg.Version)
	return err
}
