// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlc

import (
	"context"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, username, pw_hash, salt, role, ingest_key, must_change_pw)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, username, pw_hash, salt, role, ingest_key, must_change_pw, created_at
`

type CreateTenantParams struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PwHash       string `json:"pw_hash"`
	Salt         string `json:"salt"`
	Role         string `json:"role"`
	IngestKey    string `json:"ingest_key"`
	MustChangePw bool   `json:"must_change_pw"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Username,
		arg.PwHash,
		arg.Salt,
		arg.Role,
		arg.IngestKey,
		arg.MustChangePw,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PwHash,
		&i.Salt,
		&i.Role,
		&i.IngestKey,
		&i.MustChangePw,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, username, pw_hash, salt, role, ingest_key, must_change_pw, created_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PwHash,
		&i.Salt,
		&i.Role,
		&i.IngestKey,
		&i.MustChangePw,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByUsername = `-- name: GetTenantByUsername :one
SELECT id, username, pw_hash, salt, role, ingest_key, must_change_pw, created_at FROM tenants WHERE username = $1
`

func (q *Queries) GetTenantByUsername(ctx context.Context, username string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByUsername, username)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PwHash,
		&i.Salt,
		&i.Role,
		&i.IngestKey,
		&i.MustChangePw,
		&i.CreatedAt,
	)
	return i, err
}
