// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const bumpSessionEpoch = `-- name: BumpSessionEpoch :exec
UPDATE tenants SET session_epoch = session_epoch + 1 WHERE id = $1
`

func (q *Queries) BumpSessionEpoch(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, bumpSessionEpoch, id)
	return err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const getSessionEpoch = `-- name: GetSessionEpoch :one
SELECT session_epoch FROM tenants WHERE id = $1
`

func (q *Queries) GetSessionEpoch(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, getSessionEpoch, id)
	var session_epoch int64
	err := row.Scan(&session_epoch)
	return session_epoch, err
}

const setTenantChannelRate = `-- name: SetTenantChannelRate :exec
UPDATE tenants SET channel_rate = $2 WHERE id = $1
`

type SetTenantChannelRateParams struct {
	ID          string  `json:"id"`
	ChannelRate float64 `json:"channel_rate"`
}

func (q *Queries) SetTenantChannelRate(ctx context.Context, arg SetTenantChannelRateParams) error {
	_, err := q.db.Exec(ctx, setTenantChannelRate, arg.ID, arg.ChannelRate)
	return err
}

const setTenantFallbackLimit = `-- name: SetTenantFallbackLimit :exec
UPDATE tenants SET fallback_limit = $2 WHERE id = $1
`

type SetTenantFallbackLimitParams struct {
	ID            string `json:"id"`
	FallbackLimit int32  `json:"fallback_limit"`
}

func (q *Queries) SetTenantFallbackLimit(ctx context.Context, arg SetTenantFallbackLimitParams) error {
	_, err := q.db.Exec(ctx, setTenantFallbackLimit, arg.ID, arg.FallbackLimit)
	return err
}

const setTenantPassword = `-- name: SetTenantPassword :exec
UPDATE tenants SET pw_hash = $2, salt = $3, must_change_pw = FALSE WHERE id = $1
`

type SetTenantPasswordParams struct {
	ID     string `json:"id"`
	PwHash string `json:"pw_hash"`
	Salt   string `json:"salt"`
}

func (q *Queries) SetTenantPassword(ctx context.Context, arg SetTenantPasswordParams) error {
	_, err := q.db.Exec(ctx, setTenantPassword, arg.ID, arg.PwHash, arg.Salt)
	return err
}

const setTenantRole = `-- name: SetTenantRole :exec
UPDATE tenants SET role = $2 WHERE id = $1
`

type SetTenantRoleParams struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) SetTenantRole(ctx context.Context, arg SetTenantRoleParams) error {
	_, err := q.db.Exec(ctx, setTenantRole, arg.ID, arg.Role)
	return err
}
