// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const setTenantPassword = `-- name: SetTenantPassword :exec
UPDATE tenants SET pw_hash = $2, salt = $3, must_change_pw = FALSE WHERE id = $1
`

type SetTenantPasswordParams struct {
	ID     string `json:"id"`
	PwHash string `json:"pw_hash"`
	Salt   string `json:"salt"`
}

func (q *Queries) SetTenantPassword(ctx context.Context, arg SetTenantPasswordParams) error {
	_, err := q.db.Exec(ctx, setTenantPassword, arg.ID, arg.PwHash, arg.Salt)
	return err
}

const setTenantRole = `-- name: SetTenantRole :exec
UPDATE tenants SET role = $2 WHERE id = $1
`

type SetTenantRoleParams struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) SetTenantRole(ctx context.Context, arg SetTenantRoleParams) error {
	_, err := q.db.Exec(ctx, setTenantRole, arg.ID, arg.Role)
	return err
}
