package dispatch

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"net/http"
	"net/url"
	"strings"
)

var hopByHop = map[string]bool{
	"Connection": true, "Keep-Alive": true, "Proxy-Authenticate": true,
	"Proxy-Authorization": true, "Te": true, "Trailer": true,
	"Transfer-Encoding": true, "Upgrade": true,
}

// StripHopByHop removes hop-by-hop headers in place, including any named by the
// Connection header (RFC 7230).
func StripHopByHop(h http.Header) {
	for _, v := range h.Values("Connection") {
		for _, name := range strings.Split(v, ",") {
			if n := strings.TrimSpace(name); n != "" {
				h.Del(n)
			}
		}
	}
	for k := range hopByHop {
		h.Del(k)
	}
}

// clientHeadersKeyT is the context key for the original downstream request headers.
type clientHeadersKeyT struct{}

// WithClientHeaders stashes the original downstream (new-api) request headers on
// ctx so the proxy can forward them verbatim to the upstream node/channel — pure
// passthrough: the upstream sees the same request a direct cpa-key call would send,
// adding nothing (no x-app, no forged User-Agent), so CPA applies its own cloak.
func WithClientHeaders(ctx context.Context, h http.Header) context.Context {
	return context.WithValue(ctx, clientHeadersKeyT{}, h)
}

// clientHeadersFrom returns the headers stashed by WithClientHeaders, or nil.
// CopyForwardableHeaders tolerates a nil source (copies nothing).
func clientHeadersFrom(ctx context.Context) http.Header {
	h, _ := ctx.Value(clientHeadersKeyT{}).(http.Header)
	return h
}

// requestIDKeyT is the context key for the per-request correlation id stamped on
// every dispatch_logs row and linking to its stored request detail (logs-detail-1).
type requestIDKeyT struct{}

// WithRequestID stashes the per-request correlation id on ctx so every log row of
// the request carries it (and links to the one stored body+headers detail row).
func WithRequestID(ctx context.Context, id string) context.Context {
	return context.WithValue(ctx, requestIDKeyT{}, id)
}

func requestIDFrom(ctx context.Context) string {
	id, _ := ctx.Value(requestIDKeyT{}).(string)
	return id
}

// NewRequestID returns a random 128-bit hex id correlating a request's log rows
// with its stored detail. Generated by the HTTP handler and threaded via
// WithRequestID so the handler can update the detail with the response after
// dispatch returns.
func NewRequestID() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return ""
	}
	return hex.EncodeToString(b[:])
}

// requestQueryKeyT is the context key for the original downstream request URL query.
type requestQueryKeyT struct{}

// WithRequestQuery stashes the original downstream request URL query on ctx so
// the envelope strategy can inspect query parameters (e.g. ?beta=true) without
// re-parsing the URL deep inside dispatch.
func WithRequestQuery(ctx context.Context, q url.Values) context.Context {
	return context.WithValue(ctx, requestQueryKeyT{}, q)
}

// requestQueryFrom returns the query stashed by WithRequestQuery, or nil.
func requestQueryFrom(ctx context.Context) url.Values {
	q, _ := ctx.Value(requestQueryKeyT{}).(url.Values)
	return q
}

// envelopeInjectKeyT is the context key for the set of EnvelopePiece values
// that the dispatch layer should inject into the outbound request envelope.
type envelopeInjectKeyT struct{}

// withEnvelopeInject stashes the list of EnvelopePiece values to inject on ctx.
func withEnvelopeInject(ctx context.Context, pieces []EnvelopePiece) context.Context {
	return context.WithValue(ctx, envelopeInjectKeyT{}, pieces)
}

// envelopeInjectFrom returns the pieces stashed by withEnvelopeInject, or nil.
func envelopeInjectFrom(ctx context.Context) []EnvelopePiece {
	p, _ := ctx.Value(envelopeInjectKeyT{}).([]EnvelopePiece)
	return p
}

type envelopeOverrideKeyT struct{}

func withEnvelopeOverride(ctx context.Context) context.Context {
	return context.WithValue(ctx, envelopeOverrideKeyT{}, true)
}

func envelopeOverrideFrom(ctx context.Context) bool {
	v, _ := ctx.Value(envelopeOverrideKeyT{}).(bool)
	return v
}

var noCopy = map[string]bool{
	"Host": true, "Content-Length": true, "X-Api-Key": true, "Authorization": true,
}

// CopyForwardableHeaders copies src→dst, skipping hop-by-hop and auth/length
// headers the proxy re-sets itself.
func CopyForwardableHeaders(dst, src http.Header) {
	for k, vs := range src {
		ck := http.CanonicalHeaderKey(k)
		if hopByHop[ck] || noCopy[ck] {
			continue
		}
		for _, v := range vs {
			dst.Add(ck, v)
		}
	}
}
